/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Operator_Character.gltf -o src/components/OperatorCharacter.jsx -r public -k
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useMemo, useRef } from "react";
import { Color, LoopOnce, MeshStandardMaterial } from "three";
import { Group } from "three";

const WEAPONS = [
  "GrenadeLauncher",
  "AK",
  "Knife_1",
  "Knife_2",
  "Pistol",
  "Revolver",
  "Revolver_Small",
  "RocketLauncher",
  "ShortCannon",
  "SMG",
  "Shotgun",
  "Shovel",
  "Sniper",
  "Sniper_2",
] as const;

interface OperatorCharacterProps {
  color?: string;
  animation?: string;
  weapon?: string;
  [key: string]: any;
}

export function OperatorCharacter({
  color = "black",
  animation = "Idle",
  weapon = "AK",
  ...props
}: OperatorCharacterProps) {
  const group = useRef<Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/Operator_Character.gltf"
  );
  const { actions } = useAnimations(animations, group);

  if (actions["Death"]) {
    actions["Death"].loop = LoopOnce;
    actions["Death"].clampWhenFinished = true;
  }

  useEffect(() => {
    if (actions[animation]) {
      actions[animation].reset().fadeIn(0.2).play();
      return () => actions[animation]?.fadeOut(0.2);
    }
  }, [animation, actions]);

  const playerColorMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: new Color(color),
      }),
    [color]
  );

  useEffect(() => {
    // HIDING NON-SELECTED WEAPONS
    WEAPONS.forEach((wp) => {
      if (nodes[wp as keyof typeof nodes]) {
        (nodes[wp as keyof typeof nodes] as any).visible = wp === weapon;
      }
    });
  }, [weapon, nodes]);

  useEffect(() => {
    // ASSIGNING CHARACTER COLOR
    if (materials.Character_Main) {
      materials.Character_Main = playerColorMaterial;
    }
  }, [playerColorMaterial, materials]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <group name="Body">
            <skinnedMesh
              name="Cube004"
              geometry={(nodes.Cube004 as any)?.geometry}
              material={materials.Skin}
              skeleton={(nodes.Cube004 as any)?.skeleton}
              castShadow
            />
            <skinnedMesh
              name="Cube004_1"
              geometry={(nodes.Cube004_1 as any)?.geometry}
              material={materials.DarkGrey}
              skeleton={(nodes.Cube004_1 as any)?.skeleton}
              castShadow
            />
            <skinnedMesh
              name="Cube004_2"
              geometry={(nodes.Cube004_2 as any)?.geometry}
              material={materials.Pants}
              skeleton={(nodes.Cube004_2 as any)?.skeleton}
              castShadow
            />
            <skinnedMesh
              name="Cube004_3"
              geometry={(nodes.Cube004_3 as any)?.geometry}
              material={playerColorMaterial}
              skeleton={(nodes.Cube004_3 as any)?.skeleton}
              castShadow
            />
            <skinnedMesh
              name="Cube004_4"
              geometry={(nodes.Cube004_4 as any)?.geometry}
              material={materials.Black}
              skeleton={(nodes.Cube004_4 as any)?.skeleton}
              castShadow
            />
          </group>
          <primitive object={nodes.Root} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Operator_Character.gltf");